const express = require('express');
const router = express.Router();
const adminController = require('../Controller/Admin-controller');
const adminauth = require('../Middleware/Admin-middleware');
const auth = require('../Middleware/Auth-middleware');
router.route('/alluser').get(auth,adminauth,adminController.alluser);
router.route('/user/:id').get(auth,adminauth,adminController.userid);
router.route('/user/:id').patch(auth,adminauth,adminController.useridupdate);
router.route('/user/:id').delete(auth,adminauth,adminController.useriddelete);
router.route('/allseller').get(auth,adminauth,adminController.allseller);
router.route('/seller').post(auth,adminauth,adminController.sellerCreate);
router.route('/seller/verify').get(auth,adminauth,adminController.verifyseller);
router.route('/seller/:id').get(auth,adminauth,adminController.sellerid);
router.route('/seller/:id').patch(auth,adminauth,adminController.selleridupdate);
router.route('/seller/:id').delete(auth,adminauth,adminController.selleriddelete);
router.route('/allproduct').get(auth,adminauth,adminController.allProduct);
router.route('/product').post(auth,adminauth,adminController.createProduct);
router.route('/product/:id').get(auth,adminauth,adminController.productId);
router.route('/product/:id').patch(auth,adminauth,adminController.productIdUpdate);
router.route('/product/:id').delete(auth,adminauth,adminController.productIdDelete);
module.exports = router;